services:
  - type: web
    name: evercarebot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true
    healthCheckPath: /api/reminder
